sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vorbrodt/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true vorbrodt/react-test npm test
after_success:
  - docker build -t vorbrodt/multi-client ./client
  - docker build -t vorbrodt/multi-nginx ./nginx
  - docker build -t vorbrodt/multi-server ./server
  - docker build -t vorbrodt/multi-worker ./worker
  #take images and push them to docker hub, to do that we first have to login
  #login to docker CLI
  - echo "\$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  #take images an push them to docker hub
  - docker push vorbrodt/multi-client
  - docker push vorbrodt/multi-nginx
  - docker push vorbrodt/multi-server
  - docker push vorbrodt/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-multi-container"
  env: "Dockermulticontainer-env"
  bucket_name: "elasticbeanstalk-eu-north-1-355767558195"
  bucket_path: "docker-multi-container"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
